apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-container
        image: nginx
        volumeMounts:
        - name: azurefiles-volume
          mountPath: /shared/data
      volumes:
      - name: azurefiles-volume
        persistentVolumeClaim:
          claimName: afs-pvc
