V1 Manifest:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: perseverance-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: frontend-perseverance
        image: persevcareers6577/deploymentstrategy:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: perseverance-service
spec:
  type: NodePort
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30006
  type: NodePort
=====================================
  
V2 Manifest:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: perseverance-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: frontend-perseverance
        image: persevcareers6577/deploymentstrategy:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: perseverance-service
spec:
  type: NodePort
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30006
  type: NodePort
      nodePort: 30006
