apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  db_username: bXl1c2Vy      # base64 encoded value of 'myuser'
  db_password: ZGF0YWJhc2V  # base64 encoded value of 'database_password'
  ---
  apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: myimage
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db_username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db_password
